export const currentUser = {
  fullName: "Aravind Sharma",
  email: "aravind.sharma@astronova.com",
  gender: "Male",
  dob: "1994-08-14",
  tob: "06:45",
  birthPlace: "Chennai, India",
  sunSign: "Leo",
  moonSign: "Scorpio",
  risingSign: "Virgo",
  walletBalance: 1250,
  avatar: null,
};

export const consultations = {
  upcoming: [
    {
      id: "c1",
      astrologer: "Dr. Ananya Sharma",
      specialty: "Vedic Expert",
      mode: "video",
      date: "Oct 24, 2023",
      time: "4:30 PM",
      duration: "45 mins",
      topic: "Career Growth",
      status: "in3hours",
      avatarColor: "from-purple-400 to-violet-600",
    },
    {
      id: "c2",
      astrologer: "Acharya Rajesh",
      specialty: "Numerologist",
      mode: "chat",
      date: "Oct 28, 2023",
      time: "10:00 AM",
      duration: "30 mins",
      topic: "Match Making",
      status: "scheduled",
      avatarColor: "from-amber-400 to-orange-500",
    },
    {
      id: "c3",
      astrologer: "Priya Menon",
      specialty: "Tarot Reader",
      mode: "call",
      date: "Nov 02, 2023",
      time: "6:00 PM",
      duration: "20 mins",
      topic: "Relationships",
      status: "scheduled",
      avatarColor: "from-sky-400 to-blue-600",
    },
  ],
  history: [
    {
      id: "h1",
      astrologer: "Acharya Meera",
      specialty: "Vedic Call",
      mode: "call",
      date: "12 Oct 2023",
      time: "4:30 PM",
      duration: "24 mins",
      topic: "Career Growth",
      avatarColor: "from-purple-400 to-violet-600",
    },
    {
      id: "h2",
      astrologer: "Pandit Ravi Shankar",
      specialty: "Numerologist",
      mode: "chat",
      date: "05 Oct 2023",
      time: "11:15 AM",
      duration: "15 mins",
      topic: "Match Making",
      avatarColor: "from-amber-400 to-orange-500",
    },
    {
      id: "h3",
      astrologer: "Dr. Anjali Verma",
      specialty: "Vedic Call",
      mode: "video",
      date: "28 Sep 2023",
      time: "08:00 PM",
      duration: "42 mins",
      topic: "Health & Wellness",
      avatarColor: "from-rose-400 to-pink-600",
    },
    {
      id: "h4",
      astrologer: "Karan Bhatt",
      specialty: "Tarot Reader",
      mode: "chat",
      date: "19 Sep 2023",
      time: "01:20 PM",
      duration: "18 mins",
      topic: "Finance",
      avatarColor: "from-emerald-400 to-teal-600",
    },
  ],
};